### ISSUE TITLE
test qa

### ISSUE THREAD

**Issue by songjiayang** [songjiayang/prometheus_practice#10]
test

**Comment by peterzha** [comment]
why I have this error? "WARN[0568] Notify attempt 13 failed: *notify.loginAuth failed: unexpected server challenge  source=notify.go:193" 
My configuration file is showed below:

**Comment by songjiayang** [comment]
@peterzha  Maybe you need an other issue for the detail, this issue is a example for QA tag.

**Comment by peterzha** [comment]
well,I know.
