### ISSUE TITLE
wechat告警模板中隐藏instance中ip前几位如何实现！

### ISSUE THREAD

**Issue by lusains** [songjiayang/prometheus_practice#19]
import (
    	"strings"
    )
    {{- define "_alert_list" -}}
    {{- range .Alerts.Firing -}}
    --------
    告警类型：{{ .Labels.alertname }}
    告警主题: {{ .Annotations.summary }}
    告警机器：{{  strings.Join("***",strings.Split(.Labels.instance, ".")[3])}} {{ .Labels.device }}
    告警详情: {{ .Annotations.description }}
    触发时间: {{ (.StartsAt.Add 28800e9).Format "2006-01-02 15:04:05" }}
    {{ end -}}
    {{- end -}}

    {{- define "_resolve_list" -}}
    {{- range .Alerts.Resolved -}}
    ************
    告警类型：{{ .Labels.alertname }}
    告警主题: {{ .Annotations.summary }}
    告警机器：{{ strings.Join("***",strings.Split(.Labels.instance, ".")[3])}} {{ .Labels.device }}
    告警详情: {{ .Annotations.description }}
    触发时间: {{ (.StartsAt.Add 28800e9).Format "2006-01-02 15:04:05" }}
    恢复时间: {{ (.EndsAt.Add 28800e9).Format "2006-01-02 15:04:05" }}
    {{ end -}}
    {{- end -}}

    {{- define "wechat.html" -}}
    {{- if and (gt (len .Alerts.Firing) 0) (gt (len .Alerts.Resolved) 0) -}}
    Alerts Firing:{{.Alerts.Firing | len}}
    Alerts Resolved:{{len .Alerts.Resolved}}
    {{ template "_alert_list" . }}
    {{ template "_resolve_list" . }}
    {{- else -}}
      {{- if gt (len .Alerts.Firing) 0 -}}
    Alerts Firing:{{.Alerts.Firing | len}}
    {{ template "_alert_list" . }}
      {{- end -}}
      {{- if gt (len .Alerts.Resolved) 0 -}}
    Alerts Resolved:{{len .Alerts.Resolved}}
    {{ template "_resolve_list" . }}
      {{- end -}}
    {{- end -}}
    {{- end -}}

报错信息如下：failed to reload config: template: wechat.tmpl:4: function "strings" not defined，请问如何在go template中引入strings

**Comment by songjiayang** [comment]
有点意思，我回头试试

**Comment by lusains** [comment]
通过修改alertmanager源码，路径alertmanager/template/template.go文件FuncMap中添加方法	"strSplitAndJoin": func(s string) string {
		arr := strings.Split(s, ".")
		var ss = []string{"***",arr[2],".",arr[3]}
		return strings.Join(ss, "")
	},
	
	
然后在自定义的告警模板中调用即可

**Comment by songjiayang** [comment]
建议直接使用  [reReplaceAll](https://github.com/prometheus/alertmanager/blob/master/template/template.go#L140) 来实现，测试代码：

```go
package main

import (
	"html/template"
	"os"
	"regexp"
)

func main() {
	t := template.New("")
	t.Funcs(template.FuncMap(map[string]interface{}{
		"reReplaceAll": func(pattern, repl, text string) string {
			re := regexp.MustCompile(pattern)
			return re.ReplaceAllString(text, repl)
		},
	}))

	t, _ = t.Parse(`{{reReplaceAll  "([0-9]{1,3}\\.){2}" "***." .IP }}`)
	t.Execute(os.Stdout, struct {
		IP string
	}{
		"127.0.0.1",
	})
}
```

output:

```bash
***.0.1
```

对应你上面的模版可以为：

```yaml
告警机器：{{ reReplaceAll  "([0-9]{1,3}\\.){2}" "***." .Labels.instance }} {{ .Labels.device }}
```
